/* Generated By:JJTree: Do not edit this line. ASTADD_ASSIGN.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTADD_ASSIGN extends SimpleNode {
  public ASTADD_ASSIGN(int id) {
    super(id);
  }

  public ASTADD_ASSIGN(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=12b330b6f97c6a1c1a1d8fa042c5e60d (do not edit this line) */
