/* Generated By:JJTree: Do not edit this line. ASTBREAK.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTBREAK extends SimpleNode {
  public ASTBREAK(int id) {
    super(id);
  }

  public ASTBREAK(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=0867b2e6de06ca30d5622c4e066ff24c (do not edit this line) */
