/* Generated By:JJTree: Do not edit this line. ASTCONTINUE.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTCONTINUE extends SimpleNode {
  public ASTCONTINUE(int id) {
    super(id);
  }

  public ASTCONTINUE(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=c440600b4aa8fbb91a7c5763775d8501 (do not edit this line) */
