/* Generated By:JJTree: Do not edit this line. ASTCALLOUT.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTCALLOUT extends SimpleNode {
  public ASTCALLOUT(int id) {
    super(id);
  }

  public ASTCALLOUT(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=639c5ea2f38aad6df74acf11907b8974 (do not edit this line) */
