/* Generated By:JJTree: Do not edit this line. ASTDECLARATION.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTDECLARATION extends SimpleNode {
  public ASTDECLARATION(int id) {
    super(id);
  }

  public ASTDECLARATION(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=85bcd918d16f2ff8100d64c7d07e3065 (do not edit this line) */
