/* Generated By:JJTree: Do not edit this line. ASTEQUAL.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTEQUAL extends SimpleNode {
  public ASTEQUAL(int id) {
    super(id);
  }

  public ASTEQUAL(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=07ea7f85a9575a5b69944a3954a2ca53 (do not edit this line) */
