/* Generated By:JJTree: Do not edit this line. ASTGLOBAL_DECLARATION.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTGLOBAL_DECLARATION extends SimpleNode {
  public ASTGLOBAL_DECLARATION(int id) {
    super(id);
  }

  public ASTGLOBAL_DECLARATION(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=b25f634d70b354f6056325e99e3523fb (do not edit this line) */
