/* Generated By:JJTree: Do not edit this line. ASTID_SIZE.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTID_SIZE extends SimpleNode {
  public ASTID_SIZE(int id) {
    super(id);
  }

  public ASTID_SIZE(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=e38b6d428e57e801e5a9bc4548014061 (do not edit this line) */
