/* Generated By:JJTree: Do not edit this line. ASTLOCATION_OFFSET.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTLOCATION_OFFSET extends SimpleNode {
  public ASTLOCATION_OFFSET(int id) {
    super(id);
  }

  public ASTLOCATION_OFFSET(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=cac912843e684e209355e656034928b8 (do not edit this line) */
