/* Generated By:JJTree: Do not edit this line. ASTSTRING_LITERAL.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTSTRING_LITERAL extends SimpleNode {
  public ASTSTRING_LITERAL(int id) {
    super(id);
  }

  public ASTSTRING_LITERAL(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=34432a98648aa596a53c8d1db2b35588 (do not edit this line) */
