/* Generated By:JJTree: Do not edit this line. ASTTYPE_VOID.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTTYPE_VOID extends SimpleNode {
  public ASTTYPE_VOID(int id) {
    super(id);
  }

  public ASTTYPE_VOID(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=11865afdcf2378b6c710b3d5b87e2fa0 (do not edit this line) */
