/* Generated By:JJTree: Do not edit this line. ASTTYPE_INT.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTTYPE_INT extends SimpleNode {
  public ASTTYPE_INT(int id) {
    super(id);
  }

  public ASTTYPE_INT(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=d7b1ea8118a6b691b344aca4e8e069e3 (do not edit this line) */
