/* Generated By:JJTree: Do not edit this line. ASTTIMES.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTTIMES extends SimpleNode {
  public ASTTIMES(int id) {
    super(id);
  }

  public ASTTIMES(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=5d44c8543e39d8caa0037e30d1f7d22c (do not edit this line) */
