/* Generated By:JJTree: Do not edit this line. ASTUNARY_MINUS.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTUNARY_MINUS extends SimpleNode {
  public ASTUNARY_MINUS(int id) {
    super(id);
  }

  public ASTUNARY_MINUS(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=98763c593e604681c040aec55cc3378f (do not edit this line) */
