/* Generated By:JJTree: Do not edit this line. ASTVARIABLE_DECLARATION.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTVARIABLE_DECLARATION extends SimpleNode {
  public ASTVARIABLE_DECLARATION(int id) {
    super(id);
  }

  public ASTVARIABLE_DECLARATION(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=72c385d73484393cfddc0324127880b9 (do not edit this line) */
