/* Generated By:JavaCC: Do not edit this line. DecafMeParserDefaultVisitor.java Version 6.0_1 */
public class DecafMeParserDefaultVisitor implements DecafMeParserVisitor{
  public Object defaultVisit(SimpleNode node, Object data){
    node.childrenAccept(this, data);
    return data;
  }
  public Object visit(SimpleNode node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTPROGRAM node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTFIELD_DECLARATION node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTDECLARATION node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTID_SIZE node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTMETHOD_DECLARATION node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTTYPE_VOID node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTBLOCK node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTVARIABLE_DECLARATION node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTTYPE_INT node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTTYPE_BOOLEAN node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTIF_STATEMENT node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTFOR_STATEMENT node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTRETURN_STATEMENT node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTBREAK_STATEMENT node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTCONTINUE_STATEMENT node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTASSIGN node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTADD_ASSIGN node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTSUB_ASSIGN node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTMETHOD_CALL node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTCALLOUT_CALL node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTLOCATION_OFFSET node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTOR node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTAND node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTEQUAL node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTNOT_EQUAL node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTGREATER node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTGREATER_OR_EQUAL node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTLESSER node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTLESSER_OR_EQUAL node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTPLUS node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTMINUS node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTTIMES node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTOVER node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTMODULE node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTLOGICAL_NOT node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTUNARY_MINUS node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTIDENTIFYER node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTDECIMAL_LITERAL node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTHEX_LITERAL node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTBOOL_LITERAL node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTCHARACTER_LITERAL node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTSTRING_LITERAL node, Object data){
    return defaultVisit(node, data);
  }
}
/* JavaCC - OriginalChecksum=21291beee7dacdadd8a1054b9689dacd (do not edit this line) */
